In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.linear_model import SGDRegressor
from sklearn import preprocessing
from sklearn.decomposition import PCA
from pandas.api.types import is_numeric_dtype

In [55]:
df = pd.read_csv('/content/USA_Housing.csv')
df=df.sample(frac=1)
ip = df.drop('Price',axis=1)
op = df['Price']

In [57]:
scalar = StandardScaler()
ip = scalar.fit_transform(ip)
op=op/1000000
print(op)



2067    1.616631
2089    1.025418
1885    1.269811
3346    1.161233
1155    1.248131
          ...   
653     1.246509
1266    1.555491
4657    1.169051
668     1.451078
1967    1.154270
Name: Price, Length: 5000, dtype: float64


In [35]:
X_train, X_test, y_train, y_test = train_test_split(ip, op, test_size=0.3, random_state=42)

In [36]:
train_data_x=[]
train_data_y=[]
k=5
j=0;
fold_length = len(X_train)/5
fold_length = int(fold_length)
print(fold_length)
for i in range(k):
  # print(j)
  # print(fold_length+j)
  train_data_x.append(X_train[j:fold_length+j])
  train_data_y.append(y_train[j:fold_length+j])
  j = j + fold_length

700


In [ ]:
best_regressor=None
bestr2score=0
for i in range(5):
  train_set_x =[]
  train_set_y =[]
  validation_set_x=train_data_x[i]
  validation_set_y=train_data_y[i]
  for j in range(5):
    if not(j==i):
      for k in train_data_x[i]:
        train_set_x.append(k)
      for k in train_data_y[i]:
        train_set_y.append(k)
  #print(f'train set len: {len(train_set_x)}, {len(train_set_y)}')
  m=LinearRegression()
  #print(train_set_y)
  m.fit(train_set_x,train_set_y)
  print("BETA MATRIX: ")
  print(m.coef_)
  predictions=m.predict(validation_set_x)
  print("PREDICTIDE VALUES:")
  print(predictions)
  #print("PREDICTIONS AND ACTUAL: ")
  #for p in range(len(predictions)):
    #print(f'{predictions[p]} ,{validation_set_y[p]}')
  r2s=r2_score(validation_set_y,predictions)
  print("R2 SCORE: ")
  print(r2s)
  if(best_regressor==None):
    best_regressor=m
    bestr2score=r2s
  elif(r2s>bestr2score):
    bestr2score=r2s
    best_regressor=m
  else:
    pass

  


  


In [61]:
test_predictions=m.predict(X_test)
#print(test_predictions)
r2_score_test_data=r2_score(y_test,test_predictions)
print(r2_score_test_data)

0.9201200013038857


In [ ]:
df.sample(frac=1,random_state=42)
ip1 = df.drop('Price',axis=1)
op1 = df['Price']
scalar = StandardScaler()
ip1 = scalar.fit_transform(ip1)
op1/=1000000
print(op1)
trainx,validatex,testx=np.split(ip1,[int(0.56*len(ip1)),int(0.7*len(ip1))])
trainy,validatey,testy=np.split(op1,[int(0.56*len(op1)),int(0.7*len(op1))])


In [70]:
m2=SGDRegressor(alpha=0.0,learning_rate='constant',eta0=0.001)
m3=SGDRegressor(alpha=0.0,learning_rate='constant',eta0=0.01)
m4=SGDRegressor(alpha=0.0,learning_rate='constant',eta0=0.1)
m5=SGDRegressor(alpha=0.0,learning_rate='constant',eta0=1)

In [77]:
m2.fit(trainx,trainy)
print(m2.coef_)
m3.fit(trainx,trainy)
print(m3.coef_)
m4.fit(trainx,trainy)
print(m4.coef_)
m5.fit(trainx,trainy)
print(m5.coef_)
predictions2=m2.predict(validatex)
predictions3=m3.predict(validatex)
predictions4=m4.predict(validatex)
predictions5=m5.predict(validatex)
r2s2=r2_score(validatey,predictions2)
r2s3=r2_score(validatey,predictions3)
r2s4=r2_score(validatey,predictions4)
r2s5=r2_score(validatey,predictions5)
print(r2s2)
print(r2s3)
print(r2s4)
print(r2s5)


[0.22993503 0.16481197 0.12183417 0.00209179 0.15073788]
[ 0.23437578  0.17121897  0.11533297 -0.0009717   0.16241808]
[ 0.27280192  0.12934509  0.13307936 -0.02561698  0.20852911]
[ 1.97890147e+11  3.52102579e+11  7.66872420e+11 -1.47857762e+12
  2.43382351e+12]
0.919803845708939
0.9160067928505023
0.8590557464605474
-9.480609393207405e+25


In [80]:
test_predictions_2=m2.predict(testx)
r2stest=r2_score(testy,test_predictions_2)
print(r2stest)

0.9122561931339295


In [3]:
df = pd.read_csv('/content/imports-85.data')
df.columns=["symboling", "normalized_losses",
"make", "fuel_type", "aspiration","num_doors", "body_style", "drive_wheels",
"engine_location", "wheel_base", "length", "width", "height", "curb_weight",
"engine_type", "num_cylinders", "engine_size", "fuel_system", "bore", "stroke",
"compression_ratio", "horsepower", "peak_rpm", "city_mpg", "highway_mpg", "price"]
df.replace('?',np.nan, inplace=True)
for x in df.index:
        if df.loc[x, "price"] is np.nan:
            df.drop(x, inplace = True)
for c in df.columns:
        if (is_numeric_dtype(df[c])):
            mean_val =df[c].mean()
            df[c].fillna(value=mean_val, inplace=True)
        else:
            modes = df[c].mode()
            df[c].fillna(value=modes[0], inplace=True)


In [4]:
word_val_dict={'zero':0,'one':1,'two':2,'three':3,'four':4,'five':5,'six':6,'seven':7,'eight':8,'nine':9,'ten':10,'eleven':11, 'twelve':12,'thirteen':13}
df['num_doors'].replace(word_val_dict,inplace=True)
#print(df['num_doors'])
df['num_cylinders'].replace(word_val_dict,inplace=True)
#print(df['num_cylinders'])

In [5]:
#dummy encoding (one hot) of col 'body_style'
bs_dat = pd.get_dummies(df['body_style'])
#print(bs_dat)
df.drop('body_style',axis = 1,inplace=True)
df = df.join(bs_dat)
#print(df)

#dummy encoding (one hot) of col 'drive_wheels'
dw_dat = pd.get_dummies(df['drive_wheels'])
#print(bs_dat)
df.drop('drive_wheels',axis = 1,inplace=True)
df = df.join(dw_dat)
print(df)

##label encoding
le_cols =['make', 'aspiration', 'engine_location','fuel_type']
label_encoder = preprocessing.LabelEncoder()
for c in le_cols:
    #print(df[c])
    df[c] = label_encoder.fit_transform(df[c])
    #print(df[c])

## encoding fuel_system and engine_type
#print(df['fuel_system'])
for x in df.index:
    if 'pfi' in df.loc[x, "fuel_system"]:
        df.loc[x, "fuel_system"] = 1
    else:
        df.loc[x, "fuel_system"] = 0
    
    if 'ohc'in df.loc[x, "engine_type"]:
        df.loc[x, "engine_type"] = 1
    else:
        df.loc[x, "engine_type"] = 0

     symboling normalized_losses         make fuel_type aspiration  num_doors  \
0            3               161  alfa-romero       gas        std          2   
1            1               161  alfa-romero       gas        std          2   
2            2               164         audi       gas        std          4   
3            2               164         audi       gas        std          4   
4            2               161         audi       gas        std          2   
..         ...               ...          ...       ...        ...        ...   
199         -1                95        volvo       gas        std          4   
200         -1                95        volvo       gas      turbo          4   
201         -1                95        volvo       gas        std          4   
202         -1                95        volvo    diesel      turbo          4   
203         -1                95        volvo       gas      turbo          4   

    engine_location  wheel_

In [9]:
output_values = df['price']
input_features = df.drop('price',axis = 1,inplace=False)
#print(input_features)
## Scale the input values
print("SCALING OF INPUT")
scaler= StandardScaler()
scaled_input = scaler.fit_transform(input_features)
print(scaled_input)
## split into test and train set
X_train, X_test, Y_train, Y_test = train_test_split(input_features,output_values,test_size=0.3)
## Train linear regressor 
print("FITTING LINEAR REGRESSOR and TESTING")
reg_model = LinearRegression()
reg_model.fit(X_train,Y_train)
predictions = reg_model.predict(X_test)
r2s = r2_score(Y_test,predictions)
print(f'r2_score is {r2s}')
## Perform dimensionality reduction using PCA
print("DIMENSIONALITY REDUCTION WITH PCA")
num_pca_comps = 5
pca_features = PCA(n_components=num_pca_comps)
pca_features.fit(X_train)
new_X_train = pca_features.transform(X_train)
new_X_test = pca_features.transform(X_test)
pca_reg_model = LinearRegression()
pca_reg_model.fit(new_X_train,Y_train)
pca_predictions = pca_reg_model.predict(new_X_test)
newr2s = r2_score(Y_test,pca_predictions)
print(f'r2_score with PCA, ncomponents = {num_pca_comps} is {newr2s}')

SCALING OF INPUT
[[ 1.74236779  0.90516135 -1.99613611 ... -0.20412415 -1.19959343
   1.30487651]
 [ 0.13649886  0.90516135 -1.99613611 ... -0.20412415 -1.19959343
   1.30487651]
 [ 0.93943333  0.9900733  -1.83463642 ... -0.20412415  0.83361577
  -0.76635604]
 ...
 [-1.46937007 -0.96290147  1.39535728 ... -0.20412415 -1.19959343
   1.30487651]
 [-1.46937007 -0.96290147  1.39535728 ... -0.20412415 -1.19959343
   1.30487651]
 [-1.46937007 -0.96290147  1.39535728 ... -0.20412415 -1.19959343
   1.30487651]]
FITTING LINEAR REGRESSOR and TESTING
r2_score is 0.864556646845123
DIMENSIONALITY REDUCTION WITH PCA
r2_score with PCA, ncomponents = 5 is 0.8266696738567305
