In [35]:
import numpy as np
import imageio as iio
from scipy import stats as st
arr=np.array([1,2,3,4,5,6])
print(arr[::-1])

[6 5 4 3 2 1]


In [4]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1.flatten('C'))
print(array1.flatten('F'))

[1 2 3 2 4 5 1 2 3]
[1 2 1 2 4 2 3 5 3]


In [5]:
 arr1 = np.array([[1, 2], [3, 4]]) 
 arr2 = np.array([[1, 2], [3, 4]])
 compare_arrs = arr1==arr2
 print(compare_arrs)

[[ True  True]
 [ True  True]]


In [6]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
mode1=st.mode(x)
mode2=st.mode(y)
print(mode1)
ctr=0
print("indices: ")
for i in x:
  if i == mode1[0][0]:
    print(ctr)
  ctr+=1

print(mode2)
print("inices: ")
ctr=0
for i in y:
  if i == mode2[0][0]:
    print(ctr)
  ctr+=1





ModeResult(mode=array([1]), count=array([5]))
indices: 
0
5
7
8
9
ModeResult(mode=array([1]), count=array([3]))
inices: 
0
1
2


In [7]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg.sum())
print(gfg.sum(axis=1))
print(gfg.sum(axis=0))

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [8]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(np.trace(n_array))
w, v = np.linalg.eig(n_array)
print("eigenvalues: ",w)
print("eigenvectors: ",v)
print("inverse: ")
print(np.linalg.inv(n_array))
print("determinant: ")
print(np.linalg.det(n_array))

176
eigenvalues:  [98.16835147 28.097044   49.73460452]
eigenvectors:  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
inverse: 
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
determinant: 
137180.0000000001


In [9]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print(p*q)
print(np.matmul(p,q))
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
print(np.matmul(p,q))


[[ 4 10]
 [12 21]]
[[16 19]
 [26 31]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]


In [10]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(x,y))
print(np.outer(x,y,out=None))
print(np.cross(x,y))

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[-20   4   7]
 [-84  36  20]]


In [16]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
print(np.abs(array))
print(np.percentile(array,25,0,out=None))
print(np.percentile(array,25,1,out=None))
print(np.percentile(array,50,0,out=None))
print(np.percentile(array,50,1,out=None))
print(np.percentile(array,75,0,out=None))
print(np.percentile(array,75,1,out=None))
print(np.mean(array,0))
print(np.mean(array,1))
print(np.median(array,0))
print(np.median(array,1))
print(np.std(array,0))
print(np.std(array,1))





[[1 2 3]
 [4 5 6]]
[-2.75 -0.25 -3.75]
[-0.5 -5. ]
[-1.5  1.5 -1.5]
[ 1. -4.]
[-0.25  3.25  0.75]
[2.  0.5]
[-1.5  1.5 -1.5]
[ 0.66666667 -1.66666667]
[-1.5  1.5 -1.5]
[ 1. -4.]
[2.5 3.5 4.5]
[2.05480467 4.78423336]


In [18]:
 a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
 print(np.floor(a))
 print(np.ceil(a))
 print(np.round(a))
 print(np.trunc(a))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-2. -2. -0.  0.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]


In [41]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
val_and_ind_dict = {}
index=0
for i in array:
  if not(i in val_and_ind_dict):
    val_and_ind_dict[i]=[]
  val_and_ind_dict[i].append(index)
  index+=1
x=np.sort(array)
print(x)
for i in x:
  print(val_and_ind_dict[i])
print(x[:4])
print(x[-1:-6:-1])
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
for i in array:
  if type(i)==int:
    print(i)
for i in array:
  if type(i)==float:
    print(i)

[ 10  16  16  52  54  62 453]
[0]
[3, 4]
[3, 4]
[1]
[5]
[2]
[6]
[10 16 16 52]
[453  62  54  52  16]
